### ISSUE TITLE
centos7 ，php7.2使用碰到一些问题，盼望解答

### ISSUE THREAD

**Issue by siqinglin** [myziyue/aliyun-mq-client-php#1]
你好，感谢提供扩展， 碰到使用上的问题，能否解答一下。 

WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.

centos7  PHP7.2

**Comment by evan2884** [comment]
这个是由于他sdk的一个问题，你可以把java的sdk里有个/jre/lib//libsunec.so文件拷贝到当前目录下，就不会有这个问题里，应该是他sdk的一个问题

**Comment by siqinglin** [comment]
> 这个是由于他sdk的一个问题，你可以把java的sdk里有个/jre/lib//libsunec.so文件拷贝到当前目录下，就不会有这个问题里，应该是他sdk的一个问题

感谢回复， 问题解决，不过libsunec.so放到当前目录，使用上就比较不方便了。 这有办法修复一下吗？

**Comment by evan2884** [comment]
这个问题是阿里云官方sdk的问题，没办法解决，不过这个问题可以忽略，不影响正常使用。就是不太好看

**Comment by siqinglin** [comment]
> 这个问题是阿里云官方sdk的问题，没办法解决，不过这个问题可以忽略，不影响正常使用。就是不太好看

ok, 我封装一下， 统一放一个libsunec.so进去，也能接受这个WARNING， 多谢大佬分享此项目

**Comment by evan2884** [comment]
不客气，感谢你的关注
