### ISSUE TITLE
php7.1 zend_empty_string  make  cpp 问题，会支持php7.1吗

### ISSUE THREAD

**Issue by siqinglin** [myziyue/aliyun-mq-client-php#2]
zend/classimpl.cpp: In static member function ‘static int Php::ClassImpl::getClosure(zval*, zend_class_entry**, zend_function**, zend_object**)’:
zend/classimpl.cpp:307:35: error: ‘zend_empty_string’ was not declared in this scope
     function->function_name     = zend_empty_string;            // should not be null, as this is free'ed by zend when doing exception handling
                                   ^
make: *** [shared/zend/classimpl.o] Error 1

PHP-CPP] make && make install

**Comment by evan2884** [comment]
没有在PHP7.1环境中测试过，我们的环境都是php7.2。后续我会考虑对PHP7.1支持下。谢谢你的建议

**Comment by evan2884** [comment]
@siqinglin 你这个问题是在编译PHP-CPP的时候出现的问题吧！如果是PHP7.1环境的话，建议使用PHP-CPP 2.1.4版本，就不会出现上面的问题了，你可以试试看！

**Comment by siqinglin** [comment]
> @siqinglin 你这个问题是在编译PHP-CPP的时候出现的问题吧！如果是PHP7.1环境的话，建议使用PHP-CPP 2.1.4版本，就不会出现上面的问题了，你可以试试看！

感谢回复，我这边现在测试一下

**Comment by siqinglin** [comment]
> > @siqinglin 你这个问题是在编译PHP-CPP的时候出现的问题吧！如果是PHP7.1环境的话，建议使用PHP-CPP 2.1.4版本，就不会出现上面的问题了，你可以试试看！
> 
> 感谢回复，我这边现在测试一下

忘了反馈给你，这边PHP-CPP换成2.1.4版本之后，没问题了， 谢谢。
