### ISSUE TITLE
运行后段错误

### ISSUE THREAD

**Issue by dotpub** [myziyue/aliyun-mq-client-php#3]
你好, 我是CentOS7 php 7.3.23 php-cpp 2.2.0 编译成功并且安装好了扩展, 但是在运行consumer或者producer的php example后会直接报段错误. 请问是哪里出了问题呢? 
# php order-consumer.php
段错误

**Comment by evan2884** [comment]
试着php-cpp用最新的版本
```
# git clone https://github.com/CopernicaMarketingSoftware/PHP-CPP.git
# cd PHP-CPP
# make && make install
```

**Comment by evan2884** [comment]
我已经更新了阿里云的sdk，你可以试试新的版本

**Comment by dotpub** [comment]
好的, 感谢, 我先试试

**Comment by dotpub** [comment]
用了最新版PHP-CPP, 阿里云的SDK也重新装了, 但是还是会报错呀....

```
# php producer.php
# Log directory is: /root/logs
# 段错误
```

然后日志文件也是空的, 没有内容...

**Comment by evan2884** [comment]
> 用了最新版PHP-CPP, 阿里云的SDK也重新装了, 但是还是会报错呀....
> 
> ```
> # php producer.php
> # Log directory is: /root/logs
> # 段错误
> ```
> 
> 然后日志文件也是空的, 没有内容...

**Comment by evan2884** [comment]
问题已经修复，你可以尝试下v1.2.1版本
